# Generated by Django 5.0.4 on 2024-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_At',
        ),
    ]
