# Generated by Django 5.0.4 on 2024-04-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_prive',
            new_name='unit_price',
        ),
    ]
